import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import Image from "next/image";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col items-center h-screen justify-center bg-gray-300">
        <h2 className="p-4 text-2xl">Hello World</h2>
        <Link href="/about">
          <a href="#" className="p-4 text-xl bg-black text-white rounded-xl">
            Click here for About Me Page
          </a>
        </Link>
        <p className="p-2 text-lg text-center ">
          Gideon won because he trusted God. No other method to be saved.
        </p>
      </div>
    </>
  );
};

export default Home;
